version: '3.7'
services:
  # Run the repository tests
  test-package:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-test
      args:
        CODE_DIR: "/code"  # Directory containing the repository's code.
        TEST_DIR: "/test"  # Directory from which to execute the tests.
    volumes:
    - ./:/code
    entrypoint: "python -m pytest /code/tests"