ARG PYTHON_VERSION=3.7.6

FROM python:${PYTHON_VERSION}-stretch

CMD ["bash"]

ENV CODE_ROOT="/home"

RUN mkdir -p /tmp

WORKDIR "/tmp"

COPY requirements.txt .

RUN pip install -r requirements.txt

WORKDIR "${CODE_ROOT}"
