# Docker image for testing the package.
#
# All of the commands below are run from the repository root.
#
# Build:
#   docker build -t cookiecutter-data-science:latest - < dockerfiles/Dockerfile-test
#
# Run:
#   docker run --name cookiecutter-data-science-container --rm -it cookiecutter-data-science:latest

ARG PYTHON_VERSION=3.7

FROM python:${PYTHON_VERSION}-slim-buster

CMD ["bash"]

ARG CODE_DIR="/code"
ARG TEST_DIR="/test"

RUN mkdir -p $CODE_DIR
WORKDIR $CODE_DIR
COPY requirements.txt .
RUN python -m pip install --force -r requirements.txt && rm requirements.txt

WORKDIR $TEST_DIR
